defmodule MyApp.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:calendar_event, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text, null: false
      add :start_on, :utc_datetime, null: false
      add :created_date, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_date, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    drop table(:calendar_event)
  end
end